# See https://github.com/bettermarks/.github#git-hooks for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/bettermarks/.github
    # to get the latest SHA use `gh api /repos/bettermarks/.github/commits/HEAD -q .sha`
    rev: b8bcd419de6a66a6b3a5d7ca3197b801348690be
    hooks:
      - id: no-commit-to-default-branch
        # the default branch of the repository containing this yaml file
        args: [master]
      - id: pre-commit-autoupdate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:

    # These are the most critical checks.
    #
    - id: check-ast

    # Some basic sanitization.
    #
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: double-quote-string-fixer
    - id: check-docstring-first
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: debug-statements

    # Checking data formats.
    #
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml

    # Check for secrets.
    #
    # - id: check-private-key
    # - id: detect-aws-credentials

    # Try to catch some faux-pas.
    #
    # - id: no-commit-to-branch
    #   args: [--branch, master]
    - id: check-added-large-files
      args: [--maxkb=1000]
    - id: check-merge-conflict
    - id: check-symlinks

    # Try to catch some more obscure things.
    #
    - id: check-executables-have-shebangs
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: fix-encoding-pragma
      args: [--remove]

    # This checks that all links to our VCS are permalinks. How oddly specific!
    - id: check-vcs-permalinks

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    - id: pyupgrade
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
    - id: isort
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    - id: black
  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.49'
    hooks:
    - id: check-manifest
