name: Test

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Test with pytest
      if: always()
      run: cd $GITHUB_WORKSPACE && ./pytest
      env:
        PYTHONUNBUFFERED: 1
